import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { 
  DocumentTextIcon,
  UserIcon,
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  LockClosedIcon,
  ArrowPathIcon,
  ScaleIcon,
  EnvelopeIcon
} from '@heroicons/react/24/outline';

function Terms() {
  const [activeSection, setActiveSection] = useState(null);

  const sections = [
    {
      id: 'intro',
      title: 'Introduction',
      icon: <DocumentTextIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'Thank you for choosing KOLCO COMMERCE PRIVATE LIMITED ("GoGetWell AI","Go Get Well", "we," "our," or "us"). These Terms of Service ("Terms") govern your use of our AI-powered medical tourism platform, including our software applications, websites, and any other services we offer (collectively, "Services"). By accessing or using our Services, you agree to be bound by these Terms.' }
      ]
    },
    {
      id: 'registration',
      title: 'Registration and Access',
      icon: <UserIcon className="h-6 w-6" />,
      content: [
        { type: 'heading', text: 'Minimum Age' },
        { type: 'text', text: 'You must be at least 18 years old to use our Services. If you are under 18, your use of the Services must be supervised by a parent or legal guardian who consents to these Terms on your behalf.' },
        { type: 'heading', text: 'Account Registration' },
        { type: 'text', text: 'You must provide accurate and complete information to register for an account. For healthcare facilitators, this includes valid business information. You are responsible for all activities under your account and must maintain the confidentiality of your credentials.' }
      ]
    },
    {
      id: 'use',
      title: 'Use of Our Services',
      icon: <ShieldCheckIcon className="h-6 w-6" />,
      content: [
        { type: 'heading', text: 'Permitted Use' },
        { type: 'text', text: 'Subject to compliance with these Terms, you may access and use our Services for medical tourism purposes. You must comply with all applicable laws, including the Information Technology Act, 2000, and any other relevant regulations related to healthcare and tourism.' },
        { type: 'heading', text: 'Prohibited Activities' },
        { type: 'list', items: [
          'Infringe, misappropriate, or violate anyone\'s rights, including patient privacy rights.',
          'Modify, copy, lease, sell, or distribute any part of our Services.',
          'Attempt to reverse-engineer or discover the source code of our AI-powered Services.',
          'Automatically extract data without our permission.',
          'Use output generated by the Services for any purpose that could have a legal or material impact on a third party.',
          'Interfere with the functionality of our medical tourism platform.'
        ]}
      ]
    },
    {
      id: 'ip',
      title: 'Intellectual Property Rights',
      icon: <LockClosedIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'We and our affiliates own all rights, title, and interest in the Services, including any content, software, and other intellectual property related to our AI-powered medical tourism solutions.' }
      ]
    },
    {
      id: 'content',
      title: 'Content',
      icon: <ArrowPathIcon className="h-6 w-6" />,
      content: [
        { type: 'heading', text: 'User Content' },
        { type: 'text', text: 'You may provide input to the Services ("Input"), including medical information, and receive output ("Output") such as treatment recommendations. You retain ownership of the Input you provide, and we assign to you all rights in the Output generated by the Services, subject to these Terms.' },
        { type: 'heading', text: 'Our Use of Content' },
        { type: 'text', text: 'We may use your Input and Output to develop, improve, and provide our medical tourism Services. If you do not want us to use your content for these purposes, please contact us.' }
      ]
    },
    {
      id: 'warranties',
      title: 'Disclaimer of Warranties',
      icon: <ExclamationTriangleIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'OUR SERVICES ARE PROVIDED "AS IS." WHILE WE STRIVE FOR ACCURACY IN OUR AI-POWERED RECOMMENDATIONS, WE DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.' }
      ]
    },
    {
      id: 'liability',
      title: 'Limitation of Liability',
      icon: <ScaleIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'To the maximum extent permitted by law, we are not liable for any indirect, incidental, consequential, or punitive damages, or loss of profits, revenue, data, or business opportunities resulting from your use of our Services.' }
      ]
    },
    {
      id: 'changes',
      title: 'Changes to These Terms',
      icon: <ArrowPathIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'We may modify these Terms from time to time. If we make material changes, we will notify you by updating the effective date at the top of these Terms.' }
      ]
    },
    {
      id: 'contact',
      title: 'Contact Us',
      icon: <EnvelopeIcon className="h-6 w-6" />,
      content: [
        { type: 'text', text: 'If you have any questions about these Terms or our medical tourism services, please contact us at hello@gogetwell.ai.' }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-cyan-50 to-white">
      <div className="max-w-7xl mx-auto py-16 px-4">
        {/* Header Section */}
        <motion.div 
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="relative inline-block mb-8">
            <h1 className="text-5xl font-bold text-cyan-700 mb-4 relative z-10">
              <span className="bg-clip-text text-transparent bg-gradient-to-r from-cyan-600 to-cyan-800">
                Terms of Service
              </span>
            </h1>
            <div className="absolute -top-4 -left-4 w-24 h-24 bg-cyan-100 rounded-full opacity-50"></div>
            <div className="absolute -bottom-4 -right-4 w-16 h-16 bg-cyan-200 rounded-full opacity-50"></div>
          </div>
          <p className="text-xl text-cyan-900 max-w-4xl mx-auto">
            Welcome to GoGetWell AI. These Terms of Service govern your use of our AI-powered medical tourism platform and services.
          </p>
          <div className="mt-4 text-cyan-700 font-medium">
            Effective Date: October 4, 2024
          </div>
        </motion.div>

        {/* Content Sections */}
        <div className="grid lg:grid-cols-3 gap-8">
          {/* Navigation */}
          <div className="lg:col-span-1 space-y-4">
            {sections.map((section, index) => (
              <motion.button
                key={section.id}
                onClick={() => setActiveSection(activeSection === section.id ? null : section.id)}
                className={`w-full text-left p-6 rounded-xl transition-all duration-300 ${
                  activeSection === section.id
                    ? 'bg-cyan-700 text-white shadow-lg'
                    : 'bg-white text-cyan-900 hover:bg-cyan-50'
                }`}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.3, delay: index * 0.1 }}
              >
                <div className="flex items-center gap-4">
                  <div className={`p-3 rounded-full ${
                    activeSection === section.id ? 'bg-white/20' : 'bg-cyan-100'
                  }`}>
                    {React.cloneElement(section.icon, {
                      className: `h-6 w-6 ${activeSection === section.id ? 'text-white' : 'text-cyan-600'}`
                    })}
                  </div>
                  <span className="font-semibold">{section.title}</span>
                </div>
              </motion.button>
            ))}
          </div>

          {/* Content Display */}
          <div className="lg:col-span-2 bg-white rounded-2xl shadow-lg p-8">
            {activeSection ? (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
              >
                {sections.find(s => s.id === activeSection)?.content.map((item, index) => (
                  <div key={index} className="mb-6">
                    {item.type === 'heading' ? (
                      <h3 className="text-lg font-semibold text-cyan-700 mb-2">{item.text}</h3>
                    ) : item.type === 'list' ? (
                      <ul className="list-disc ml-6 space-y-2">
                        {item.items.map((listItem, idx) => (
                          <li key={idx} className="text-cyan-900">{listItem}</li>
                        ))}
                      </ul>
                    ) : (
                      <p className="text-cyan-900">{item.text}</p>
                    )}
                  </div>
                ))}
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3 }}
                className="text-center py-12"
              >
                <div className="bg-cyan-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                  <DocumentTextIcon className="h-8 w-8 text-cyan-700" />
                </div>
                <h3 className="text-xl font-semibold text-cyan-700 mb-2">Select a Section</h3>
                <p className="text-cyan-600">Choose a topic from the menu to view detailed information about our terms of service.</p>
              </motion.div>
            )}
          </div>
        </div>

        {/* Contact Section */}
        <motion.div 
          className="mt-16 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <h2 className="text-2xl font-bold text-cyan-700 mb-4">Have Questions?</h2>
          <p className="text-cyan-900 mb-6">We're here to help with any questions about our terms of service.</p>
          <a 
            href="mailto:hello@gogetwell.ai" 
            className="inline-flex items-center gap-2 bg-cyan-700 text-white px-6 py-3 rounded-full shadow-lg hover:bg-cyan-600 transition-colors"
          >
            <EnvelopeIcon className="h-5 w-5" />
            Contact Us
          </a>
        </motion.div>
      </div>
    </div>
  );
}

export default Terms; 